### ISSUE TITLE
Ist sie nicht quelloffen, weil die Ergebnisse schwer zu reproduzieren sind?

### ISSUE THREAD

**Issue by ScottishFold007** [JetRunner/LaPraDoR#4]
Ist nicht Open Source, weil die Ergebnisse schwer zu reproduzieren sind? Es ist ratsam, solche Arbeiten mit Ergebnissen ohne konsequente Umsetzung in Zukunft nicht mehr zu veröffentlichen.

**Comment by JetRunner** [comment]
Thanks for your interest in our work. I hope this issue was posted in good faith.

The only thing missing here is the training code. You can reproduce all the results in our paper with the model checkpoint and inference code we provide.
