### ISSUE TITLE
Which instructions for fine-tuning

### ISSUE THREAD

**Issue by jxmorris12** [JetRunner/LaPraDoR#5]
Hi, thanks for the awesome work!

I saw this note in the README: "For fine-tuning, please follow the instructions in [BEIR repo](https://github.com/beir-cellar/beir).". I looked through the BEIR repository, and it's not obvious to me which instructions you're referring to. Can you provide a little more insight how we might use the BEIR code for fine-tuning LAPRADOR? thanks.

**Comment by JetRunner** [comment]
It's here :)

https://github.com/beir-cellar/beir/blob/main/examples/retrieval/training/train_msmarco_v3.py

**Comment by jxmorris12** [comment]
thank you
